### ISSUE TITLE
Implement a way to do a password matching validation

### ISSUE THREAD

**Issue by thaberkern** [nealstewart/backbone.validations#16]
I use the validation plugin for a project some while. So far the only thing I'm missing is the possibility to implement an password matching validator. Sure I'm able to build a custom validator but this will only have access to the current attribute (i.e. passwordRepeat) and the values of the model. In this case I would need access to the current attribute and the other newly set attributes.

Any idea how this can be solved?

**Comment by PhilipChen** [comment]
I've forked this repo and made my changes for a basic password validator.

https://github.com/PhilipChen/backbone.validations/commit/51e28a657f93ce1cdc035f95348757dc359a5cf6

Note that the password attribute to compare with must be set in the model before the required events will fire.

**Comment by nealstewart** [comment]
Implement this at the view layer, not the model layer. Check to see if the passwords match before setting them in the model.
