### ISSUE TITLE
"required" no longer works with backbone 0.9

### ISSUE THREAD

**Issue by tomaszkubacki** [nealstewart/backbone.validations#17]
As of  0.9 backbone disallows invalid state. "Can't create an invalid model" error is thrown

**Comment by thaberkern** [comment]
Problem should be solved with Backbone 0.9.1 isn't it?

**Comment by nsb** [comment]
Yep, 0.9.1 fixed this issue for me.

**Comment by tomaszkubacki** [comment]
yea work for me too now - thanks for info
