### ISSUE TITLE
named event does not fire

### ISSUE THREAD

**Issue by davisford** [nealstewart/backbone.validations#18]
Hi, I'm trying to use your library, and for the life of me, I couldn't figure out why named events were not firing:

this.model.bind('error:name', function(model, errs) { /\* do something */ });

So, I decided to clone your repo, and run the tests, sure enough the test that checks this is failing.  Any idea what's up?

**Comment by nealstewart** [comment]
It's broken with the new version of Backbone. :(

I need to give Backbone.Validations some love anyway, so I'll take a look tonight. Thanks for the issue!

**Comment by davisford** [comment]
Thanks Neal,

Your little framework looked perfect for me.  I was trying to find
something very lightweight that would allow me to trap on invalid events
from individual form fields vs. the backbone (whole model is invalid) way,
yet still maintaining validation in the model, where it belongs.

I'm just now looking at  https://github.com/thedersen/backbone.validation as
an alternative.  If you do get it fixed, let me know - I'd like to use it
if you resolve the issue.

Thanks,
Davis

On Thu, Feb 9, 2012 at 10:57 AM, Neal Stewart <
reply@reply.github.com

**Comment by nealstewart** [comment]
@davisford This was fixed by the pull request that was brought in fairly recently.
