### ISSUE TITLE
Custom error messages?

### ISSUE THREAD

**Issue by al6x** [nealstewart/backbone.validations#24]
Is there a way to specify custom error messages? 

Something like `{ name: ["can't be blank!"] }` instead of `{ name: ["required"] }`

**Comment by nealstewart** [comment]
The idea of this plugin is to keep that sort of logic out of your model. Your view should be handling the display of the error (I.E. the text you need).

**Comment by al6x** [comment]
Hmmm, I see Your point. But sometimes it's very handy to have this feature, also it's not directly coupled with UI it's more like a human-friendly description of error instead of a some constant.

And from the development point of view - it would cost only about 3-10 lines of code, so maybe it's worth to add it?

**Comment by nealstewart** [comment]
The suggested use of this library is for you to maintain a mapping of error types to messages in your view layer, or as a separate view helper module. I maintain that messages like "can't be blank" are view layer business.
