### ISSUE TITLE
Add more informations on errors

### ISSUE THREAD

**Issue by thaberkern** [nealstewart/backbone.validations#8]
If I define validations on a model the validation is called when I save the model. So far so good, but in the error handler of the save model you only get an array of the error types (i.e. required) but that is of no help without the field-name the error had occured.

**Comment by nealstewart** [comment]
Hmm. This sounds screwy. I'll check up on it. :)

**Comment by thaberkern** [comment]
That would be great. We are the beginnig of a large project where we like to use the validation part :)

**Comment by thaberkern** [comment]
Any news on this?

**Comment by nealstewart** [comment]
I'll take a look at it tonight. ;) Startup life and 60 hour weeks have me distracted!

**Comment by nealstewart** [comment]
Hey. Took a look at this. Added some tests. This seems to be working for me. Is your issue that the individual error callbacks don't include the name? Post a snippet.

**Comment by nealstewart** [comment]
If you use an error callback like so

``` javascript
model.bind('error:attributeName', function() {});
```

Then errors will look like so:

``` javascript
["errorName", "otherErrorName"]
```

**Comment by nealstewart** [comment]
If you bind to ALL of the errors for an object, like so:

``` javascript
model.bind('error', function() {});
```

Then you'll get an error object like so:

``` javascript
{"attributeName": ["errorName", "otherErrorName"]}
```

**Comment by nealstewart** [comment]
Is this unintuitive? Maybe the same error object should be returned in both cases.

**Comment by thaberkern** [comment]
Mhmm, I have an Model like this

´´´
Inventory = Backbone.Model.extend({

```
validate: {
    name: {
        required: true
    },
   number: {
        required: true
   }
}
```

});
´´´
With a model instance I tried:

´´´
           this.model.bind('error', function(model, errs) {
                // [1]
            });

```
        this.$('#inventory-name').removeClass('invalid');
        this.model.save(
            {
                'name': inventoryName
            },
            {
                success: function(model, response) {
                    //...
                },
                error: function(model, response){
                    // [2]
                }
        });
```

´´´

I`m landing in [2] not in [1] and the response object of [2] only contains "required"

Timo

**Comment by nealstewart** [comment]
Gotcha! Cool. I'll write a test and fix this on my lunch. ;)

**Comment by nealstewart** [comment]
I added a test. It looks as if this behaviour is currently what you're looking for.

https://github.com/n-time/backbone.validations/commit/c8398212ac968374a6c2f5052e148dbbf68b66c8

**Comment by nealstewart** [comment]
It looks as if this is working as you expect... Try pulling master again.

**Comment by thaberkern** [comment]
Have done so. Got it working now. Thanks for your time and keep up your great work!
