### ISSUE TITLE
`validate` method doesn't conform to Backbone API

### ISSUE THREAD

**Issue by dcuddeback** [nealstewart/backbone.validations#9]
With Backbone.js (before installing Backbone.Validations), the `validate` method expects a hash of attributes. It seems that after installing Backbone.Validations, the `validate` method expects the model object.

Without `Backbone.Validations`:

```
var post = new Post;
post.validate({title : "Foo"});
```

With `Backbone.Validations`, the above call will throw a `TypeError`. Instead, I have to pass `post` to `validate`:

```
var post = new Post;
post.validate(post);
```

The documentation for Backbone says that it will pass the attributes to `validate`. Being able to pass attributes directly to `validate` will be useful when validating an attribute while the user types. http://documentcloud.github.com/backbone/#Model-validate

**Comment by nealstewart** [comment]
Shitty deal. You're right. Will fix!

**Comment by ryantofteland** [comment]
I'm interested in this issue as well. If I want to manually force validation on my model and my model is already populated - what is the recommended approach for that use case? Based on Backbone's `model.validate` documentation I'm assuming the approach would be to do something like this (assuming I'm in a Backbone View):

```
this.model.validate(this.model.toJSON());
```

Is that along the lines with what your fix will support? It would be nice to just be able to call `this.model.validate();` to avoid the redundancy - but maybe that starts to conflict with Backbone's definition.

**Comment by dcuddeback** [comment]
I can see use cases for validating the entire model and validating just the attributes passed to `validate`. For example, if you want to validate a field as the user types, you probably only want to validate that one field. Validating the whole model will cause errors to be displayed on form fields that the user hasn't reached yet. On the other hand, there may be times that you want to validate the whole model, such as when the form loses focus.

Backbone will only pass the attributes that changed. From the docs: "`validate` is called before `set` and `save`, and is passed the attributes that are _about to be updated_" (emphasis mine). In order to support validating the entire model with `this.model.validate()`, the `validate` method would have to merge the new attributes with the old ones. I would propose the following API:

```
this.model.validate();
```

validates the whole model.

```
this.model.validate({foo : "bar"});
```

validates the whole model with the `foo` attribute set to `bar`. As far as I understand the Backbone.js API, this conforms to what Backbone expects you to do with the `validate` method. That is, it validates the whole model before it will be attempted to be saved. However, to support validating as the user types, I would add an options parameter:

```
this.model.validate({foo : "bar"}, {validateModel : false});
```

Or maybe just:

```
this.model.validate({foo : "bar"}, false)
```

if you don't think there will be any more options. This might diverge from the Backbone docs a bit, but it will still be compatible.

These are just my thoughts. I haven't been working with Backbone enough to have a strong sense of what the best approach is. What are your guys' thoughts?

**Comment by ryantofteland** [comment]
I agree with that API and I think it covers these scenarios well. 

I'm not sure I understand your comment on `validate()` needing to "_merge the new attributes with the old ones_" when calling `this.model.validate()`. I would think the validation would just run with whatever values are in `this.model.attributes`. There shouldn't be a need to merge anything in this case, should there?

**Comment by dcuddeback** [comment]
@ryantofteland In the case of `this.model.validate()`, you're right, it will just validate against `this.model.attributes`. But, when you call `.set()` on a model, the new attributes are sent as the first argument to `validate`. By merging the new attributes with the old ones, I mean that if `validate` receives a set of attributes, it should validate the model as if those new attributes were set. In other words, it will validate `this.model.attributes` with any attributes provided in the argument as an override.

```
validate : function (attributes) {
  attributesToValidate = clone(this.model.attributes);
  extend(attributesToValidate, attributes);
  /* validate attributesToValidate */
}
```

Backbone sends new attributes to `validate` _before_ adding them to `this.model.attributes`. For example:

```
User = Backbone.Model.extend({
  validate: function (attributes) {
    console.log("validate:", attributes);
    return -1;
  }
});

user = new User;
user.get("name");        // => undefined
user.set({name: "Joe"})  // => logs 'validate: {name: "Joe"}', returns false
user.get("name");        // => undefined
```

Backbone doesn't set attributes if the validation fails.

**Comment by ryantofteland** [comment]
@dcuddeback Yeah - that makes sense in terms of calling `validate()` without passing anything in. Wasn't sure if I was on the same page there or not. 

I'm not sure I agree that passing in attributes to validate should merge and update the model. That seems counter-intuitive to me. That behavior could be achieved through calling `this.model.set({Name: "Joe"})` to trigger validation or instead call `this.model.set({Name: "Joe"}, {silent: true})` and then calling `this.model.validate()`. The plugin also gives you the option to subscribe to field specific error events ex: `this.model.bind('error:name', function(model, errs) {});`. In that case you could call `set` to trigger validation as granular as needed (per keyup as user types) and handle that individual field as the event is triggered.

Am I interpreting you correctly?

**Comment by dcuddeback** [comment]
@ryantofteland I'm not advocating that `validate` should update the model. I agree that it would be counter-intuitive. To answer your question: no, you're not interpreting my comment correctly. I must not have explained myself well. I'll try again:

I'm going to intermix excerpts from Backbone's documentation into my explanation: http://documentcloud.github.com/backbone/#Model-validate

It's important to understand the context under which `validate` is called. It's method signature is `model.validate(attributes)` (that's according to the Backbone.js documentation). Notice that it takes an argument called `attributes`. This is _not_ the same as `this.attributes` (the model's attributes). You need to understand this difference for my previous comments to make sense.

When you call `.set({foo: "bar"})` on a model, `{foo: "bar"}` is passed _by Backbone_ to your model's `validate` method. (Relevant excerpt from documentation: "`validate` is called before `set` and `save`, and is passed the attributes that _are about to be updated_.") Your suggestion of calling `this.model.set({foo: "bar"})` to force validations doesn't work if you don't account for the attributes passed to `validate`, because `{foo: "bar"}` will _not_ be part of `this.model.attributes` until _after_ `validate` passes. (Relevant excerpt: "`set` and `save` will not continue if `validate` returns an error.") In other words, `set` only sets the attributes on `this.model.attributes` if `validate` succeeds.

Look at my example again. Notice that when calling `user.set({name: "Joe"})`, `validate` is called automatically and is passed `{name: "Joe"}`. Had I added another line to `validate` to log `this.attributes`, you'd see that `this.attributes` is empty: `{}`. Also notice that `"name"` is _not_ set on `user` after the call to `set`, because the validations failed. This it the default Backbone.js behavior.

As for setting the attributes passed to `validate` on the model: that's not what I meant. Take another look at my pseudo-implementation of `validate` in my previous comment. Notice that `attributesToValidate` is cloned from `this.model.attributes`. The `validate` method does not mutate `this.model.attributes`. (Actually, in `validate`, that should be referred to as `this.attributes`. Maybe that's a source of confusion. Sorry about that. That's a bug in my pseudo-code.)

The reason this merging is necessary is because `this.attributes` contains the _old_ attributes (before calling `set`), and the `attributes` argument in `validate` contains the _new_ attributes that are to be set. But only the attributes that changed. It's not a complete set of new attributes.

I hope this is more clear.

**Comment by ryantofteland** [comment]
@dcuddeback Sorry - about the confusion. Thanks for the clarification. I think I'm on the same page now. I definitely understand the difference here between the attributes on the model and those being passed to validate. I should have just looked closer at the implementation example on your last comment and I would have caught up to you quicker.

I think my confusion came along the lines of needing to do a merge of attributes at all. I'd be fine with just validating only the attributes that are passed to the method - unless they are undefined at which point `validate` would just grab a clone of `this.model.attributes` and validate everything. If attributes are passed to `validate`, I'd propose that just those attributes are validated (and never merged). This stays closer to the Backbone definition and would remove the need of an option to set `validateModel` to true/false as you had in your example: `this.model.validate({foo : "bar"}, {validateModel : false});`

Going with the "don't merge" approach, then it would not be possible to call something like this: `this.model.validate({foo : "bar"});` and have it validate the whole model with 'bar' being the value for the foo attribute. I think that's fine. The workaround for that scenario would instead be:

```
this.model.set({foo: "bar"}, {silent: true});
this.model.validate(); //validates everything with foo having a value of "bar".
```

To modify your example then, I picture something like this:

```
validate : function (attributes) {
    attributes || (attributes = this.model.toJSON())
    /* validate attributes */
}
```

To be honest I'm fine whether there's a merge option or not. I think we're in agreement on the big picture.

**Comment by dcuddeback** [comment]
@ryantofteland Glad we're on the same page. The reason I thought it makes sense to merge the attributes is because a validation might be conditional. For example, you might only need to validate field "foo" if "bar" is undefined. In those circumstances, it would be necessary to merge the attributes, so that you know which validations need to be run.

Honestly, I don't know how often this occurs on the front-end. I occasionally see it in back-end code. I think hacking around it with `set(..., {silent: true})` breaks the intended semantics of `set`. I believe the `validate` method is intended to be a guard that protects your model from ever having invalid attributes, which is why the attributes aren't set when `validate` fails. If conditional validations are rare in front-end code, then I agree that it can simply validate the passed-in attributes. It would be possible to override `validate` in user code to add attribute merging if necessary, anyway.

**Comment by nealstewart** [comment]
I think that the problem you're discussing, having errors displayed for form elements prior to the user interacting with them, is something that can be handled nicely in the view layer. The error can occur, but don't display it until it matters to the client - after they interact with the form element.

**Comment by nealstewart** [comment]
I'm going to fix this soon - by matching Backbone's interface to the letter - fairly soon. Pretty busy time of year, though.

**Comment by ryantofteland** [comment]
Thanks - looking forward to it.

**Comment by nealstewart** [comment]
The validate interface is now maintained.
https://github.com/n-time/backbone.validations/commit/550460ec1b3fc7cddc61016ce50d2c03c8f93130
